name: Upload Instagram Reels from Drive

on:
  workflow_dispatch:      # تشغيل يدوي
  schedule:
    - cron: "0 */6 * * *"  # كل 6 ساعات

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: تثبيت ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
        
      - name: تثبيت gdown
        run: pip install gdown
        
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install instagrapi google-api-python-client google-auth-httplib2 google-auth-oauthlib requests pillow

      - name: Run uploader
        env:
          SERVICE_ACCOUNT_JSON_B64: ${{ secrets.SERVICE_ACCOUNT_JSON_B64 }}
        run: python main.py
