name: Upload Google Drive Videos to Instagram

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # كل 6 ساعات، عدل حسب الحاجة

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install instagrapi gdown requests

      - name: Save session.json
        run: |
          echo "${{ secrets.IG_SESSION }}" > session.json

      - name: Run Instagram uploader
        env:
          FOLDER_ID: ${{ secrets.FOLDER_ID }}
        run: python main.py
