name: Upload Reels from Drive Folder

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"  # كل 4 ساعات

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install instagrapi gdown requests pillow

      - name: Save session.json
        run: |
          printf "%s" '${{ secrets.IG_SESSION }}' > session.json

      - name: Run uploader
        run: python main.py
